In [1]:
import torch
import numpy as np

In [3]:
t = torch.tensor([
    [0,1,0],
    [2,0,2],
    [0,3,0]
], dtype=torch.float32)

In [4]:
t.sum()

tensor(8.)

In [5]:
t.sum().numel()

1

In [7]:
t.sum().numel() > t.numel()

False

In [8]:
t.prod()

tensor(0.)

In [9]:
t.mean()

tensor(0.8889)

In [10]:
t.std()

tensor(1.1667)

In [11]:
t34 = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
], dtype=torch.float32)

In [12]:
t34.sum(dim=0) #apply sums to the first dim, i.e., sum all elements of the dim, which are arrays, so, sum(arrays)

tensor([6., 6., 6., 6.])

In [15]:
t34.sum(dim=1) 
#apply sum to each element of the first dim, i.e., apply sum to each array of the dim, 
#i.e., sum all elements of each array

tensor([ 4.,  8., 12.])

In [16]:
t2 = torch.tensor([
    [1,0,0,2],
    [0,3,3,0],
    [4,0,0,5]
],dtype=torch.float32)

In [17]:
t2.max() #returns the max value per say

tensor(5.)

In [18]:
t2.argmax() #returns the index of the max value

tensor(11)

In [20]:
t2.flatten()

tensor([1., 0., 0., 2., 0., 3., 3., 0., 4., 0., 0., 5.])

In [21]:
t3 = torch.tensor([
    [1,2,3],
    [4,5,6],
    [7,8,9]
], dtype=torch.float32)

In [22]:
t3.mean()

tensor(5.)

In [23]:
t3.mean().item()

5.0

In [27]:
t3.mean(dim=0).tolist()

[4.0, 5.0, 6.0]

In [28]:
t3.mean(dim=0).numpy()

array([4., 5., 6.], dtype=float32)