In [2]:
import torch

In [3]:
t = torch.tensor([1,2,3])
print(t.dtype)
print(t.device)
print(t.layout)

torch.int64
cpu
torch.strided


In [4]:
t2 = torch.tensor([1.,2.,3.])

In [5]:
t+t2 #tensors should be of the same device and dtype to be computed against one another

RuntimeError: expected device cpu and dtype Float but got device cpu and dtype Long

In [7]:
torch.eye(2) #returns the identity tensor

tensor([[1., 0.],
        [0., 1.]])

In [8]:
torch.ones(2,2) #returns a tensor of ones in the shape desired

tensor([[1., 1.],
        [1., 1.]])

In [10]:
torch.zeros(2,2) #returns a tensor of zeroes in the shape desired

tensor([[0., 0.],
        [0., 0.]])

In [11]:
torch.rand(2,2) #returns a random tensor in the shape desired

tensor([[0.3466, 0.8462],
        [0.5668, 0.0940]])

In [12]:
import numpy as np

In [13]:
tnp = np.array([1,2,3])

In [20]:
t1 = torch.Tensor(tnp)
t2 = torch.tensor(tnp) #<- best for day by day usage
t3 = torch.as_tensor(tnp) #<- best for memory optimization
t4 = torch.from_numpy(tnp)
t5 = torch.tensor(tnp, dtype=torch.float64)

In [21]:
print(t1)#class constructor sets dtype to the global default dtype, i.e. float32
print(t2)#factory constructor dynamic obj creation infer dtype
print(t3)#factory function infer dtype
print(t4)#factory function infer dtype
print(t5)#forces the dtype

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3])
tensor([1, 2, 3])
tensor([1., 2., 3.], dtype=torch.float64)


In [22]:
tnp[0] = 0
tnp[1] = 0
tnp[2] = 0

In [23]:
print(t1)#class constructor sets dtype to the global default dtype, i.e. float32
print(t2)#factory constructor dynamic obj creation infer dtype
print(t3)#factory function infer dtype sticks to the original data like a pointer 
print(t4)#factory function infer dtype sticks to the original data like a pointer
print(t5)#forces the dtype

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([0, 0, 0])
tensor([0, 0, 0])
tensor([1., 2., 3.], dtype=torch.float64)


In [24]:
#Reshaping Ops

In [25]:
rt1 = t1.reshape(1,3) #always remember n*m = o*p, i.e., dimensions multiplication should be equal to the original
rt2 = t1.reshape(3,1)

In [27]:
print(rt1)
print(rt2)

tensor([[1., 2., 3.]])
tensor([[1.],
        [2.],
        [3.]])


In [32]:
#rank 2 tensor with 2 axis
# axis 1 = link 3
# axis 2 = link 4
r2a2t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
], dtype=torch.float32)


In [36]:
r2a2t.size()

<function Tensor.size>

In [34]:
r2a2t.shape

torch.Size([3, 4])

In [35]:
len(r2a2t.shape)

2

In [37]:
r2a2t.numel()

12

In [48]:
rt1=r2a2t.reshape(3,4)
rt2=r2a2t.reshape(6,2)
rt3=r2a2t.reshape(1,12)
rt4=r2a2t.reshape(2,2,3)

In [49]:
print(rt1)
print(rt2)
print(rt3)
print(rt4)

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])
tensor([[1., 1.],
        [1., 1.],
        [2., 2.],
        [2., 2.],
        [3., 3.],
        [3., 3.]])
tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
tensor([[[1., 1., 1.],
         [1., 2., 2.]],

        [[2., 2., 3.],
         [3., 3., 3.]]])


In [52]:
rt5 = rt3.squeeze()
rt6 = rt5.unsqueeze(dim=0)

In [54]:
print(rt5)
print(rt5.shape)
print(rt6)
print(rt6.shape)
#Flatten tensor is to rank down your tensor, i.e. project a tensor to a single axis

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])
torch.Size([12])
tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


In [55]:
def flatten(t):
    t = t.reshape(1,-1) #-1 tells figure out the rest of the shape and shoot it to one axis only, i.e., flatten it
    t = t.squeeze()
    return t

In [65]:
print(flatten(rt1))

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])
