In [21]:
import torch
import numpy as np

In [2]:
t1 = torch.tensor([
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1],
])
t2 = torch.tensor([
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2],
])
t3 = torch.tensor([
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3],
])

In [3]:
t = torch.stack((t1,t2,t3)) #concatenate the list of tensors to a new axis, this is our batch, so our batch size is 3

In [4]:
t.shape

torch.Size([3, 4, 4])

In [5]:
t = t.reshape(3,1,4,4) # adding the color channel by reshaping another dimension of 1 

In [6]:
t

tensor([[[[1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1]]],


        [[[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]]],


        [[[3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3]]]])

In [9]:
print("---------------------------------------------------")
print("The first image of the batch: \n", t[0])
print("---------------------------------------------------")
print("The image first color channel: \n", t[0][0])
print("---------------------------------------------------")
print("The first row on the height of the image: \n", t[0][0][0])
print("---------------------------------------------------")
print("The first element of width of the image, and therefore the pixel: \n", t[0][0][0][0])
print("---------------------------------------------------")

---------------------------------------------------
The first image of the batch: 
 tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]])
---------------------------------------------------
The image first color channel: 
 tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])
---------------------------------------------------
The first row on the height of the image: 
 tensor([1, 1, 1, 1])
---------------------------------------------------
The first element of width of the image, and therefore the pixel: 
 tensor(1)
---------------------------------------------------


In [10]:
tflats = t.flatten(start_dim=1)#start_dim=1 skips the flat for the batch dimension

In [11]:
tflats

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [13]:
tflats.shape

torch.Size([3, 16])

In [14]:
t1 + t2

tensor([[3, 3, 3, 3],
        [3, 3, 3, 3],
        [3, 3, 3, 3],
        [3, 3, 3, 3]])

In [15]:
t2 - t1

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [16]:
t1 * t2

tensor([[2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2]])

In [34]:
ts = torch.tensor([
    [0,1],
    [2,3]
], dtype=torch.float32)
tb = torch.tensor([2,4], dtype=torch.float32)

In [35]:
ts+tb #tb was broadcasted into the shape of the higher dimension tensor of its operation

tensor([[2., 5.],
        [4., 7.]])

In [36]:
tb+ts #order doesn't matter

tensor([[2., 5.],
        [4., 7.]])

In [37]:
np.broadcast_to(tb.numpy(), ts.shape) #here is how broadcast is done

array([[2., 4.],
       [2., 4.]], dtype=float32)

In [38]:
ts.eq(0)

tensor([[ True, False],
        [False, False]])

In [39]:
ts.ge(0)

tensor([[True, True],
        [True, True]])

In [40]:
ts.gt(0)

tensor([[False,  True],
        [ True,  True]])

In [41]:
ts.lt(0)

tensor([[False, False],
        [False, False]])

In [42]:
ts.le(0)

tensor([[ True, False],
        [False, False]])

In [43]:
ts.abs()

tensor([[0., 1.],
        [2., 3.]])

In [44]:
ts.sqrt()

tensor([[0.0000, 1.0000],
        [1.4142, 1.7321]])

In [45]:
ts.neg()

tensor([[-0., -1.],
        [-2., -3.]])

In [47]:
ts.neg().abs()

tensor([[0., 1.],
        [2., 3.]])